### ISSUE TITLE
记事日历 在新版报错

### ISSUE THREAD

**Issue by xiaoyangh** [oopsguy/WechatSmallApps#5]
![0d3a855e-60d3-4a98-b165-08c53ab6d65f](https://cloud.githubusercontent.com/assets/1456254/20513541/7e0c2582-b0c1-11e6-8b75-220010b1f7a0.png)

**Comment by oopsguy** [comment]
由于官方IDE更新到了0.11.112301版本，移除了对Promise的支持，造成事项助手不能正常运行，解决此问题，在项目中引入第三方兼容库Bluebird支持Promise，代码已经整合到项目代码中。
